export const GLOSSARY_VISUALIZATION_IDS = [
  "alpha-centauri",
  "habitable-zone",
  "exomoon",
  "tidal-heating",
  "roche-limit",
  "radial-velocity",
  "direct-imaging",
  "transit-timing-variation",
  "hox-genes",
  "niche-partitioning",
  "countercurrent-exchange",
  "bioluminescence",
  "cladogram",
  "allometry",
  "lotka-volterra-equations",
  "chirality",
  "umwelt",
  "occams-razor",
  "tidal-locking",
  "atmospheric-disequilibrium",
  "half-life",
  "quantum-locking",
  "hadley-cell",
  "percolation-theory",
  "integrated-information-theory",
  "biological-market",
  "shannon-entropy",
  "daisyworld",
  "cohesion-tension",
  "dynamic-soaring",
  "square-cube-law",
  "transmission-spectroscopy",
  "coriolis-effect",
] as const;

export type GlossaryVisualizationId = (typeof GLOSSARY_VISUALIZATION_IDS)[number];
