import fs from "node:fs";
import path from "node:path";
import { chapterImagesDir } from "./content-paths";

// Resolve a chapter's full-bleed background image (fig-99-background.png),
// generated by gen-images like any other figure. Returns a public URL path or
// undefined when none exists yet, so the page falls back to the plain void.

export function getChapterBackgroundImage(slug: string): string | undefined {
  const file = path.join(chapterImagesDir(slug), "fig-99-background.png");
  return fs.existsSync(file)
    ? `/images/chapters/${slug}/fig-99-background.png`
    : undefined;
}
