import fs from "node:fs";
import path from "node:path";
import { PUBLIC_IMAGES_ROOT } from "./content-paths";

// Resolve a glossary term's cover image from disk. Generated by
// scripts/gen-glossary-covers.ts to public/images/glossary/{id}.png. Returns a
// public URL path or undefined when no image exists yet (UI falls back to a
// gradient), mirroring the chapter cover-image resolver.

export function getGlossaryCoverImage(id: string): string | undefined {
  const file = path.join(PUBLIC_IMAGES_ROOT, "glossary", `${id}.png`);
  return fs.existsSync(file) ? `/images/glossary/${id}.png` : undefined;
}
