import fs from "node:fs";
import path from "node:path";
import { PUBLIC_IMAGES_ROOT } from "./content-paths";

// Resolve a glossary term's cover image from disk. Generated by
// scripts/gen-glossary-covers.ts to public/images/glossary/{id}.png and then
// optimized to {id}.webp (the deployed format). Prefers the lighter .webp, and
// falls back to the .png original, or undefined when neither exists (the UI
// falls back to a gradient) - mirroring the chapter cover-image resolver.

export function getGlossaryCoverImage(id: string): string | undefined {
  const webp = path.join(PUBLIC_IMAGES_ROOT, "glossary", `${id}.webp`);
  if (fs.existsSync(webp)) return `/images/glossary/${id}.webp`;
  const png = path.join(PUBLIC_IMAGES_ROOT, "glossary", `${id}.png`);
  return fs.existsSync(png) ? `/images/glossary/${id}.png` : undefined;
}
