import fs from "node:fs";
import path from "node:path";
import { PUBLIC_IMAGES_ROOT } from "./content-paths";

// Resolve a page's full-bleed background image from disk. Generated by
// scripts/gen-page-backgrounds.ts to public/images/pages/{id}.png. Returns a
// public URL path or undefined when no image exists yet (the page then renders
// on the plain void background), mirroring the glossary cover-image resolver.

export type PageBackgroundId = "chapters" | "glossary" | "authors" | "parts" | "timeline";

export function getPageBackground(id: PageBackgroundId): string | undefined {
  const file = path.join(PUBLIC_IMAGES_ROOT, "pages", `${id}.png`);
  return fs.existsSync(file) ? `/images/pages/${id}.png` : undefined;
}
