import fs from "node:fs";
import path from "node:path";
import { staticUrl } from "@/lib/static-url";
import { PUBLIC_IMAGES_ROOT } from "./content-paths";
import manifest from "./image-manifest.json";

// Resolve a page's full-bleed background image from disk. Generated by
// scripts/gen-page-backgrounds.ts to public/images/pages/{id}.png. Returns a
// public URL path or undefined when no image exists yet (the page then renders
// on the plain void background), mirroring the glossary cover-image resolver.

export type PageBackgroundId = "chapters" | "glossary" | "authors" | "parts" | "timeline";

export function getPageBackground(id: PageBackgroundId): string | undefined {
  const manifestUrl = (manifest.pageBackgrounds as Record<string, string> | undefined)?.[id];
  if (manifestUrl) return manifestUrl;
  const file = path.join(PUBLIC_IMAGES_ROOT, "pages", `${id}.png`);
  return fs.existsSync(file) ? staticUrl(`/images/pages/${id}.png`) : undefined;
}
